### PR TITLE
Added the ability to obtain the encoder RPM.

### PR DESCRIPTION
**Pull request by rprediger**
Added the ability to obtain the encoder RPM.
Added verification of time between steps in case of encoder stop

### CODE REVIEW

**Comment by mathertel** [comment]
Thanks for this getRPM function.
The change also changes the behavior of the existing getMillisBetweenRotations() function and potentially breaks compatibility.

After merging I will re-establish the old getMillisBetweenRotations implementation and move the new implementation into getRMP.

**Comment by rprediger** [comment]
Glad to help!
I just realized that the number of steps is understood which limits the library. I am unaware of other sensors with different number of steps, but I believe there must be. I will make this correction and send it to you, if you wish.

**Comment by mathertel** [comment]
I did it. Just take the head version.

**Comment by Llaves** [comment]
maybe it's a language issue, but in the US, RPM is revolutions per minute, ie, full turns.  As implemented, the function is returning ticks per minute. To get RPM (at least as I interpret the term), you need to know how many ticks per revolution the encoder generates and divide the computed value by that number.

**Comment by rprediger** [comment]
> maybe it's a language issue, but in the US, RPM is revolutions per minute, ie, full turns. As implemented, the function is returning ticks per minute. To get RPM (at least as I interpret the term), you need to know how many ticks per revolution the encoder generates and divide the computed value by that number.

Hello @Llaves thanks for your question, but reviewing the code I am still convinced that the function performs the calculation correctly.
The function calculates the RPM (revolutions per minute) based on the time of the last step. However, if the pulses have ceased, the function assumes the time between the last tick and the current time to calculate the RPM. The function also assumes that the encoder has 20 pulses per revolution. For example:
If the last pulse took 25ms then one rotation takes 25ms * 20 pulses = 500ms = 0.5s (period)
To transform the period into revolutions per second (RPS or frequency), it is done (1 / period) and finally to transform RPS into RPM it is multiplied by 60.
RPS = 1 / 0.5 = 2;
RPM = 2 * 60 = 120;
NOTE: As time is measured in milliseconds, it is necessary to convert to seconds, so the calculation looks like this:
RPM = (1 / ((last tick time * 20) / 1000)) * 60; 
Making the simplifications we have:
RPM = 60000 / (last tick time * 20);

**Comment by Llaves** [comment]
The concern I have with this code is that it contains a magic number - 20. Not every encoder has 20 ticks per rev. The dirt-cheap common ones used in many Arduino projects do have 20 counts, but that's no always the case. It would be better to make this a member variable of the class, include a setter, and perhaps initialize to a default value of 20.

**Comment by rprediger** [comment]
Hello @Llaves,
I have already expressed my concern about this here:
> Glad to help!
> I just realized that the number of steps is understood which limits the library. I am unaware of other sensors with different number of steps, but I believe there must be. I will make this correction and send it to you, if you wish.

And @mathertel said that he had already solved it here:
> I did it. Just take the head version.

So I didn't want to make any other suggestions related to that.

**Comment by Llaves** [comment]
Sorry - I should have read the thread more carefully. But now I'm confused. @mathertel  says it's solved in the head version. There is only a single branch on github, the master branch. In this branch the magic number 20 still appears. Am I looking in the wrong place? The last commit for the .cpp file is Jan 29. Your comment about number of steps was posted on Jan 30, as was the post that it was corrected.

**Comment by Llaves** [comment]
@rprediger wrote:
>I am unaware of other sensors with different number of steps, but I believe there must be. 

This [style of encoder](https://www.aliexpress.com/item/1005001509739801.html?spm=a2g0o.productlist.0.0.2d4134c2rl18Wb&algo_pvid=0360ae48-c98d-46af-bfc4-62f3751aa035&algo_expid=0360ae48-c98d-46af-bfc4-62f3751aa035-1&btsid=0bb0622d16222123623878167eea29&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) is commonly used in CNC controllers for manually jogging the machine. It has 100 pulses per rev.

This [style ](https://www.aliexpress.com/item/4000797890690.html?spm=a2g0o.productlist.0.0.95d2e8b8Wxejoc&algo_pvid=eb725e94-854d-453c-a3bf-76e5c92747a4&algo_expid=eb725e94-854d-453c-a3bf-76e5c92747a4-25&btsid=0b0a556b16222121059233041eff76&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)can be used for high accuracy sensing of shaft position (where "high" is a relative term.) It generates 600 pulses/rev.

**Pull request merged**
